In [1]:
import numpy as np

### Questão 1 (peso 0,10):
Considere a figura abaixo. Um robô é colocado a 1 metro de uma mesa cuja duas de suas pernas estão sobre o eixo y 0 , como mostrado. O topo da mesa está a 1 metro de altura da base do robô, e tem 1 metro quadrado. Um sistema de coordenadas **o1x1y1z1** é fixado na intersecção de suas arestas da mesa, como mostrado. Um cubo medindo 20cm de
lado é colocado no centro da mesa, com um sistema de coordenadas **o2x2y2z2** estabelecido no seu centro, como mostrado. Uma câmera é posicionada a 2 metros acima do topo da mesa, com um sistema de coordenadas **o3x3y3z3** . Ache as transformações homogêneas relacionando cada um desses sistemas ao sistema da base o **0x0y0z0** . Ache a transformação homogênea relacionando o sistema **o2x2y2z2** ao sistema **o3x3y3z3**.

<img src="img/1.jpg" width="400px">

#### Resposta
para **0x0y0z0** e **o1x1y1z1** temos somente a translação em y e em z, portanto a matriz de transformação será R = I (identidade) * t

In [2]:
np.array([
    [1,0,0,0], # translação em x = 0
    [0,1,0,1], # translação em y = 1
    [0,0,1,1], # translação em z = 1
    [0,0,0,1]  # dimensão extra da matriz homogênea
])

array([[1, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

para **0x0y0z0** e **o2x2y2z2**, também não temos rotação, portanto a parte de rotação da matriz seguirá sendo a identidade

In [3]:
np.array([
    [1,0,0,-0.5], # translação em x = -0.5m
    [0,1,0, 1.5], # translação em y = 1 + 0.5m (distancia ate a mesa + 50cm até o centro da mesa)
    [0,0,1, 1.1], # translação em z = 1m + 0.1m (distancia até a altura da mesa + distancia até centro do cubo, que é em 10cm a mais de altura)
    [0,0,0, 1. ]  # dimensão extra da matriz homogênea
])

array([[ 1. ,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ,  1.5],
       [ 0. ,  0. ,  1. ,  1.1],
       [ 0. ,  0. ,  0. ,  1. ]])

para **0x0y0z0** e **o3x3y3z3**, teremos a rotação e a translação a seguir:

In [4]:
rot_o3x3y3z3 = np.array([
   # colunas 
   # x,y,z
    [0,1, 0], # eixo y novo aponta para x do sistema anterior
    [1,0, 0], # eixo x novo aponta para y do sistema anterior
    [0,0,-1], # eixo z novo aponta para -z do sistema anterior
    [0,0, 0]  # dimensão extra da matriz homogenea
])

trans_o3x3y3z3 = np.array([
    [-0.5], # translação em x = -0.5m
    [ 1.5], # translação em y = 1m + 0.5m
    [ 3. ], # translação em z = 3m
    [ 1. ]  # dimensão extra da matriz homogenea
])

np.concatenate((rot_o3x3y3z3, trans_o3x3y3z3), axis=1)

array([[ 0. ,  1. ,  0. , -0.5],
       [ 1. ,  0. ,  0. ,  1.5],
       [ 0. ,  0. , -1. ,  3. ],
       [ 0. ,  0. ,  0. ,  1. ]])

Finalmente, para a transformação homogênea relacionando o sistema **o2x2y2z2** ao sistema **o3x3y3z3**, temos a mesma rotação entre o0 e o3, pois os eixos te o0 e o2 estão alinhados.

In [5]:
rot2_para_3 = np.array([
   # colunas 
   # x,y,z
    [0,1, 0], # eixo y novo aponta para x do sistema anterior
    [1,0, 0], # eixo x novo aponta para y do sistema anterior
    [0,0,-1], # eixo z novo aponta para  -z do sistema anterior
    [0,0, 0]  # dimensão extra da matriz homogenea
])

trans2_para_3 = np.array([
    [0. ], # translação em x = 0m
    [0. ], # translação em y = 0m
    [1.9], # translação em z = 1.9m, pois precisamos considerar os 10 cm da superficie da mesa até o centro do cubo
           # por essa razão, ao invés de 2m, ficariam 2m - 10cm, 1.9m
    [1. ]  # dimensão extra da matriz homogenea
])

np.concatenate((rot2_para_3, trans2_para_3), axis=1)

array([[ 0. ,  1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -1. ,  1.9],
       [ 0. ,  0. ,  0. ,  1. ]])

### Questão 2 (peso 0,10):
Considere o manipulador de 5 graus de liberdade mostrado em sua
posição zero. Derive as equações da sua cinemática direta, utilizando, para tanto, a convenção
de Denavit-Hartenberg clássica. Não é preciso escrever a matriz geral do manipulador, basta
desenvolver as matrizes que relacionam os elos. Derive as equações que resolvem cada um
dos ângulos de orientação em X-Y-Z da ferramenta em função das variáveis de junta, na
expressão mais simples possível.

<img src="img/2.jpg" width="400px">

**Resposta**

A especificação da matriz A é feita seguindo-se a ordem de
transformações homogêneas de translação e rotação que reposicionam
o sistema i – 1 ao i:
- rotação em torno do eixo Z<sub>i-1</sub> do ângulo $\theta$<sub>i</sub> entre os elos;
- translação ao longo do eixo Z<sub>i-1</sub> da distância d<sub>i</sub> entre os elos;
- translação ao longo do eixo X<sub>i</sub> (eixo X<sub>i-1</sub> atual) do comprimento do elo (L<sub>i</sub> );
- rotação em torno do eixo X<sub>i</sub> do ângulo ($\alpha$<sub>i</sub> ).

= Rot(Z, $\theta$<sub>i</sub> ) . Trans (0, 0, d<sub>i</sub> ) . Trans(L<sub>i</sub>, 0, 0). Rot(X, $\alpha$<sub>i</sub> )

In [6]:
%%html
<style>
table {float:left}
</style>

**Parâmetros de elos**:

| Elo | rot_z  | trans_z | trans_x | rot_x |
|-----|--------|---------|---------|-------|
| l1  | 0      | 0       | 0       | 0     |
| l2  | $\theta$<sub>1</sub> | 0       | 0       | 0     |
| l3  | $\theta$<sub>3</sub> | l2      | 0       | 45    |
| l4  | $\theta$<sub>4</sub> | l4      | 0       | 45    |
| l5  | $\theta$<sub>5</sub> | l5      | 0       | 0     |

In [7]:
print("Matriz A, elo 1, não há transformações pois há somente uma translação de l1 no eixo y:")

np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

Matriz A, elo 1, não há transformações pois há somente uma translação de l1 no eixo y:


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [8]:
print("Matriz A, elo 2, há apenas a rotação de theta no eixo Z:")

text = """
np.array([
        [cos(theta1), -sen(theta1), 0, 0]
        [sen(theta1), cos(theta1) , 0, 0]
        [0          , 0           , 1, 0]
        [0          , 0           , 0, 1]
])
"""
print(text)

Matriz A, elo 2, há apenas a rotação de theta no eixo Z:

np.array([
        [cos(theta1), -sen(theta1), 0, 0]
        [sen(theta1), cos(theta1) , 0, 0]
        [0          , 0           , 1, 0]
        [0          , 0           , 0, 1]
])



In [9]:
print("Matriz A, elo 3, rotação em theta3, translação l2 em Z, rotação de 45º em X.")
print("As matrizes serão apresentadas na vertical por falta de espaço:")

text = """
rotação de theta em Z

        [cos(theta3), -sen(theta3), 0, 0]
        [sen(theta3),  cos(theta3), 0, 0]
        [0          , 0           , 1, 0]
        [0          , 0           , 0, 1]

                           .

translação l2 em Z

        [1, 0, 0, 0 ]
        [0, 1, 0, 0 ]
        [0, 0, 1, l2]
        [0, 0, 0, 1 ]

                           .

rotação de 45º em X

        [0, 0       , 0          , 0]
        [0, cos(45) , -sin(45)   , 0]
        [0, sin(45) , cos(45)    , 0]
        [0, 0       , 0          , 1]

"""

print(text)
text = """
Matriz final:

        [cos(theta3), -sen(theta3)*cos(45), sen(theta3)*sen(45) , 0] 
        [sen(theta3), cos(theta3)*cos(45) , -cos(theta3)*sen(45), 0]
        [0          , sen(45)             , cos(45)             ,l2]
        [0          , 0                   , 0                   , 1]
"""
print(text)

Matriz A, elo 3, rotação em theta3, translação l2 em Z, rotação de 45º em X.
As matrizes serão apresentadas na vertical por falta de espaço:

rotação de theta em Z

        [cos(theta3), -sen(theta3), 0, 0]
        [sen(theta3),  cos(theta3), 0, 0]
        [0          , 0           , 1, 0]
        [0          , 0           , 0, 1]

                           .

translação l2 em Z

        [1, 0, 0, 0 ]
        [0, 1, 0, 0 ]
        [0, 0, 1, l2]
        [0, 0, 0, 1 ]

                           .

rotação de 45º em X

        [0, 0       , 0          , 0]
        [0, cos(45) , -sin(45)   , 0]
        [0, sin(45) , cos(45)    , 0]
        [0, 0       , 0          , 1]



Matriz final:

        [cos(theta3), -sen(theta3)*cos(45), sen(theta3)*sen(45) , 0] 
        [sen(theta3), cos(theta3)*cos(45) , -cos(theta3)*sen(45), 0]
        [0          , sen(45)             , cos(45)             ,l2]
        [0          , 0                   , 0                   , 1]



In [10]:
print("Matriz A, elo 4, rotação em theta4, translação l4 em Z, rotação de 45º em X:")

text = """
Matriz final:

        [cos(theta4), -sen(theta4)*cos(45), sen(theta4)*sen(45) , 0] 
        [sen(theta4), cos(theta4)*cos(45) , -cos(theta4)*sen(45), 0]
        [0          , sen(45)             , cos(45)             ,l4]
        [0          , 0                   , 0                   , 1]
"""
print(text)

Matriz A, elo 4, rotação em theta4, translação l4 em Z, rotação de 45º em X:

Matriz final:

        [cos(theta4), -sen(theta4)*cos(45), sen(theta4)*sen(45) , 0] 
        [sen(theta4), cos(theta4)*cos(45) , -cos(theta4)*sen(45), 0]
        [0          , sen(45)             , cos(45)             ,l4]
        [0          , 0                   , 0                   , 1]



In [11]:
print("Matriz A, elo 5, rotação em theta5, translação l5 em Z:")

text = """
Matriz final:

        [cos(theta5), -sen(theta5), 0, 0 ]
        [sen(theta5), cos(theta5) , 0, 0 ]
        [0          , 0           , 1, l5]
        [0          , 0           , 0, 1 ]
"""
print(text)

Matriz A, elo 5, rotação em theta5, translação l5 em Z:

Matriz final:

        [cos(theta5), -sen(theta5), 0, 0 ]
        [sen(theta5), cos(theta5) , 0, 0 ]
        [0          , 0           , 1, l5]
        [0          , 0           , 0, 1 ]

