In [1]:
import numpy as np

### Questão 1 (peso 0,10):
Considere a figura abaixo. Um robô é colocado a 1 metro de uma mesa cuja duas de suas pernas estão sobre o eixo y 0 , como mostrado. O topo da mesa está a 1 metro de altura da base do robô, e tem 1 metro quadrado. Um sistema de coordenadas **o1x1y1z1** é fixado na intersecção de suas arestas da mesa, como mostrado. Um cubo medindo 20cm de
lado é colocado no centro da mesa, com um sistema de coordenadas **o2x2y2z2** estabelecido no seu centro, como mostrado. Uma câmera é posicionada a 2 metros acima do topo da mesa, com um sistema de coordenadas **o3x3y3z3** . Ache as transformações homogêneas relacionando cada um desses sistemas ao sistema da base o **0x0y0z0** . Ache a transformação homogênea relacionando o sistema **o2x2y2z2** ao sistema **o3x3y3z3**.

 ![image 1](img/1.jpg)

#### Resposta
para **0x0y0z0** e **o1x1y1z1** temos somente a translação em y e em z, portanto a matriz de transformação será R = I (identidade) * t

In [2]:
np.array([
    [1,0,0,0], # translação em x = 0
    [0,1,0,1], # translação em y = 1
    [0,0,1,1], # translação em z = 1
    [0,0,0,1]  # dimensão extra da matriz homogênea
])

array([[1, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

para **0x0y0z0** e **o2x2y2z2**, também não temos rotação, portanto a parte de rotação da matriz seguirá sendo a identidade

In [3]:
np.array([
    [1,0,0,-0.5], # translação em x = -0.5m
    [0,1,0, 1.5], # translação em y = 1 + 0.5m (distancia ate a mesa + 50cm até o centro da mesa)
    [0,0,1, 1.1], # translação em z = 1m + 0.1m (distancia até a altura da mesa + distancia até centro do cubo, que é em 10cm a mais de altura)
    [0,0,0, 1. ]  # dimensão extra da matriz homogênea
])

array([[ 1. ,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ,  1.5],
       [ 0. ,  0. ,  1. ,  1.1],
       [ 0. ,  0. ,  0. ,  1. ]])

para **0x0y0z0** e **o3x3y3z3**, teremos a rotação e a translação a seguir:

In [4]:
rot_o3x3y3z3 = np.array([
   # colunas 
   # x,y,z
    [0,1, 0], # eixo y novo aponta para x do sistema anterior
    [1,0, 0], # eixo x novo aponta para y do sistema anterior
    [0,0,-1], # eixo z novo aponta para -z do sistema anterior
    [0,0, 0]  # dimensão extra da matriz homogenea
])

trans_o3x3y3z3 = np.array([
    [-0.5], # translação em x = -0.5m
    [ 1.5], # translação em y = 1m + 0.5m
    [ 3. ], # translação em z = 3m
    [ 1. ]  # dimensão extra da matriz homogenea
])

np.concatenate((rot_o3x3y3z3, trans_o3x3y3z3), axis=1)

array([[ 0. ,  1. ,  0. , -0.5],
       [ 1. ,  0. ,  0. ,  1.5],
       [ 0. ,  0. , -1. ,  3. ],
       [ 0. ,  0. ,  0. ,  1. ]])

Finalmente, para a transformação homogênea relacionando o sistema **o2x2y2z2** ao sistema **o3x3y3z3**, temos a mesma rotação entre o0 e o3, pois os eixos te o0 e o2 estão alinhados.

In [5]:
rot2_para_3 = np.array([
   # colunas 
   # x,y,z
    [0,1, 0], # eixo y novo aponta para x do sistema anterior
    [1,0, 0], # eixo x novo aponta para y do sistema anterior
    [0,0,-1], # eixo z novo aponta para  -z do sistema anterior
    [0,0, 0]  # dimensão extra da matriz homogenea
])

trans2_para_3 = np.array([
    [0. ], # translação em x = 0m
    [0. ], # translação em y = 0m
    [1.9], # translação em z = 1.9m, pois precisamos considerar os 10 cm da superficie da mesa até o centro do cubo
           # por essa razão, ao invés de 2m, ficariam 2m - 10cm, 1.9m
    [1. ]  # dimensão extra da matriz homogenea
])

np.concatenate((rot2_para_3, trans2_para_3), axis=1)

array([[ 0. ,  1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -1. ,  1.9],
       [ 0. ,  0. ,  0. ,  1. ]])